export type Category =
  | 'power-control'
  | 'lighting'
  | 'security'
  | 'environmental'
  | 'access-control'
  | 'remote-control'
  | 'water-control'
  | 'voice-assistants'
  | 'networking'
  | 'bundles';

export interface Product {
  id: string;
  slug: string;
  sku: string;
  name: string;
  shortDesc: string;
  description: string;
  category: Category;
  brand: 'Tuya' | 'Smartlife' | 'TP-Link TAPO' | 'TP-Link Deco' | 'Amazon Echo' | 'Google Nest' | 'GeeWiz';
  price: number;
  comparePrice?: number;
  images: string[];
  tags: string[];
  inStock: boolean;
  featured?: boolean;
}

export const CATEGORIES: Record<Category, string> = {
  'power-control': 'Power Control',
  'lighting': 'Lighting',
  'security': 'Security',
  'environmental': 'Environmental',
  'access-control': 'Access Control',
  'remote-control': 'Remote Control',
  'water-control': 'Water Control',
  'voice-assistants': 'Voice Assistants',
  'networking': 'Mesh Wi-Fi',
  'bundles': 'Bundles',
};

export const products: Product[] = [
  {
    id: 'gw-a-sa-smart-plug-16a',
    slug: 'wifi-smart-plug-16a-tuya',
    sku: 'GW-A-SA-PLUG-16A',
    name: 'WiFi Smart Plug 16A with Energy Monitoring',
    shortDesc: 'SA plug with Tuya/Smartlife, Alexa & Google Home. Energy monitoring included.',
    description: 'Control home appliances from anywhere using the Tuya / Smart Life app. Features voice assistant support via Amazon Alexa and Google Home, scheduling, timers, and energy monitoring. South African 16A plug type. Input: 100–240V, Max load: 16A, Wi-Fi: 2.4GHz.',
    category: 'power-control',
    brand: 'Tuya',
    price: 250,
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80'],
    tags: ['smart plug', 'energy monitoring', 'alexa', 'google home', '16a', 'sa plug'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-tuya-basic-breaker-10a',
    slug: 'tuya-wifi-switch-breaker-10a-energy-monitoring',
    sku: 'GW-A-BREAKER-10A',
    name: 'Tuya WiFi Switch Breaker 10A with Energy Monitoring',
    shortDesc: 'DIN-rail smart breaker with energy monitoring, scheduling and remote control.',
    description: 'Smart circuit breaker with Tuya Wi-Fi, 10A capacity, energy monitoring (kWh), remote on/off, scheduling and overload protection. DIN rail mount. Compatible with Tuya / SmartLife, Alexa and Google Home.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['https://images.unsplash.com/photo-1601004890520-d0c09f74bfc4?w=400&q=80'],
    tags: ['breaker', 'din rail', 'energy monitoring', 'smart switch'],
    inStock: true,
  },
  {
    id: 'gw-a-63a-breaker-timer',
    slug: 'tuya-63a-smart-breaker-timer',
    sku: 'GW-A-STM10',
    name: '63A Tuya Smart Breaker with Timer',
    shortDesc: 'High-capacity 63A smart circuit breaker with scheduling and LED indicator.',
    description: '63A Tuya smart breaker with timer and LED indicator. Suitable for heavy-load applications including geysers, pool pumps and industrial equipment. Wi-Fi controlled via Tuya / SmartLife app.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-63a-breaker-timer/main.jpg'],
    tags: ['63a', 'breaker', 'geyser', 'pool pump', 'heavy load'],
    inStock: true,
  },
  {
    id: 'gw-a-63a-breaker-kwh',
    slug: 'tuya-63a-smart-breaker-kwh',
    sku: 'GW-A-BREAKER-63A-KWH',
    name: '63A Tuya Smart Breaker with kWh Monitoring',
    shortDesc: '63A breaker with real-time energy consumption monitoring.',
    description: '63A Tuya smart circuit breaker with kWh energy monitoring, remote control, and scheduling. Monitor energy usage of high-load devices like geysers and pool pumps in real time.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-63a-breaker-kwh/main.jpg'],
    tags: ['63a', 'energy monitoring', 'kwh', 'breaker'],
    inStock: true,
  },
  {
    id: 'gw-a-mini-diy-16a-switch',
    slug: 'mini-diy-16a-tuya-switch',
    sku: 'GW-A-MINI-16A',
    name: 'Mini DIY 16A Tuya In-Wall Switch Module',
    shortDesc: 'Compact in-wall relay module. Works with existing switches.',
    description: 'Miniature 16A Tuya smart switch module designed to fit behind existing wall switches. No neutral required. Compatible with Tuya / SmartLife, Alexa, Google Home and Home Assistant.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-mini-diy-16a/main.jpg'],
    tags: ['in-wall module', 'relay', 'no neutral', 'diy'],
    inStock: true,
  },
  {
    id: 'gw-a-1ch-inching-12v',
    slug: 'geewiz-1ch-inching-12v-tuya',
    sku: 'GW-A-1CH-12V',
    name: 'GeeWiz 1CH Inching/Self-Locking 12V Tuya Module',
    shortDesc: '12V relay module with inching/self-locking modes for gates, locks and automation.',
    description: 'Tuya 1-channel 12V relay module with inching and self-locking modes. Ideal for gate motors, door locks, blinds and custom automation projects. Wi-Fi controlled via Tuya / SmartLife.',
    category: 'power-control',
    brand: 'GeeWiz',
    price: 0,
    images: ['/images/products/gw-a-1ch-inching-12v/main.jpg'],
    tags: ['relay', '12v', 'gate', 'inching', 'automation'],
    inStock: true,
  },
  {
    id: 'gw-a-sf-2200w',
    slug: 'tuya-smart-switch-2200w',
    sku: 'GW-A-SF-2200W',
    name: 'Tuya WiFi Smart Switch 2200W',
    shortDesc: '2200W in-line smart switch for high-power appliances.',
    description: '2200W Tuya smart in-line switch for control of high-power appliances. Remote control, scheduling, and energy monitoring via Tuya / SmartLife app.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-sf-2200w/main.jpg'],
    tags: ['2200w', 'in-line switch', 'high power'],
    inStock: true,
  },
  {
    id: 'gw-a-30a-smart-switch',
    slug: 'tuya-wifi-smart-switch-30a',
    sku: 'GW-A-SW-30A',
    name: 'Tuya Wi-Fi Smart Switch 30A / 6600W',
    shortDesc: 'Heavy-duty 30A smart switch for geysers, HVAC and industrial loads.',
    description: '30A / 6600W Tuya smart switch. Ideal for geysers, water heaters, HVAC units and other high-draw appliances. Remote on/off, scheduling, and energy monitoring via Tuya / SmartLife app.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-30a-switch/main.jpg'],
    tags: ['30a', '6600w', 'geyser', 'hvac', 'heavy duty'],
    inStock: true,
  },
  {
    id: 'gw-a-energy-monitor-ms01',
    slug: 'tuya-energy-monitor-ms01',
    sku: 'GW-A-MS01',
    name: 'Tuya Energy Monitor MS01',
    shortDesc: 'Whole-home energy monitoring with real-time kWh tracking.',
    description: 'The Tuya MS01 energy monitor provides real-time whole-home energy consumption monitoring. Clips onto your mains cables without cutting. View usage, costs and trends in the Tuya / SmartLife app.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['https://images.unsplash.com/photo-1620714223084-8fcacc2dfd3d?w=400&q=80'],
    tags: ['energy monitor', 'whole home', 'kwh', 'electricity'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-tuya-dimmer-switch',
    slug: 'tuya-wifi-dimmer-light-switch',
    sku: 'GW-A-DIMMER',
    name: 'Tuya WiFi Smart Dimmer Light Switch',
    shortDesc: 'In-wall dimmer switch compatible with LED and halogen bulbs.',
    description: 'Tuya WiFi smart dimmer switch. Compatible with dimmable LED and halogen bulbs. No neutral required. Control brightness via app, voice or touch. Works with Alexa, Google Home and Home Assistant.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-dimmer/main.jpg'],
    tags: ['dimmer', 'led', 'light switch', 'no neutral'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-tuya-light-switch-no-neutral',
    slug: 'tuya-smart-light-switch-no-neutral',
    sku: 'GW-A-SW-NONEUTRAL',
    name: 'Tuya Smart Light Switch (No Neutral Required)',
    shortDesc: 'Drop-in smart wall switch — no neutral wire needed.',
    description: 'Tuya smart wall switch that works without a neutral wire — perfect for older SA wiring. Single gang. Touch or app control, scheduling, and voice assistant compatibility.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&q=80'],
    tags: ['light switch', 'no neutral', 'in-wall', 'single gang'],
    inStock: true,
  },
  {
    id: 'gw-tuya-led-gu10-9w',
    slug: 'tuya-led-gu10-rgbcw-9w',
    sku: 'GW-TUYA-GU10-9W',
    name: 'Tuya Smart LED GU10 RGBCW 9W',
    shortDesc: 'GU10 spotlight with full RGBCW colour, dimming and scheduling.',
    description: '9W GU10 smart LED bulb with full RGB + cool/warm white (RGBCW). 16 million colours, dimmable, schedulable. Works with Tuya / SmartLife, Alexa and Google Home. Direct replacement for standard GU10 downlights.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['https://images.unsplash.com/photo-1563207153-4be887cbcb9a?w=400&q=80'],
    tags: ['gu10', 'rgb', 'smart bulb', 'spotlight', 'led'],
    inStock: true,
  },
  {
    id: 'gw-tuya-led-gu10-7w',
    slug: 'tuya-led-gu10-rgbcw-7w',
    sku: 'GW-TUYA-GU10-7W',
    name: 'Tuya Smart LED GU10 RGBCW 7W',
    shortDesc: '7W GU10 smart spotlight with RGBCW colour control.',
    description: '7W GU10 smart LED with full RGBCW colour spectrum. Ideal for accent and display lighting. Works with Tuya / SmartLife, Alexa and Google Home.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-tuya-gu10-7w/main.jpg'],
    tags: ['gu10', 'rgb', 'smart bulb', '7w', 'led'],
    inStock: true,
  },
  {
    id: 'gw-t-smart-bulb-e27-9w',
    slug: 'tuya-smart-bulb-rgb-cw-9w-e27',
    sku: 'GW-T-BULB-E27-9W',
    name: 'Tuya Smart Bulb RGBCW 9W E27',
    shortDesc: 'E27 screw-cap smart bulb with full colour and white temperature control.',
    description: 'Tuya 9W E27 smart LED bulb with 16M colour RGBCW. Dimmable. Schedulable. Music sync mode. Compatible with Tuya / SmartLife, Alexa, Google Home and Home Assistant.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=400&q=80'],
    tags: ['e27', 'smart bulb', 'rgb', '9w', 'screw cap'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-t-smart-bulb-b22-10w',
    slug: 'tuya-smart-bulb-rgb-cw-10w-b22',
    sku: 'GW-T-BULB-B22-10W',
    name: 'Tuya Smart Bulb RGBCW 10W B22',
    shortDesc: 'B22 bayonet smart bulb — SA standard fitting with full RGBCW.',
    description: 'Tuya 10W B22 bayonet smart LED bulb with RGBCW colour. South African standard fitting. Dimmable, schedulable, music sync. Works with Tuya / SmartLife, Alexa and Google Home.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['https://images.unsplash.com/photo-1518710843675-2540dd79065c?w=400&q=80'],
    tags: ['b22', 'bayonet', 'smart bulb', 'rgb', '10w'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-t-smart-led-downlight',
    slug: 'tuya-smart-led-downlight',
    sku: 'GW-T-DOWNLIGHT',
    name: 'Tuya Smart LED Downlight',
    shortDesc: 'Recessed smart downlight with warm/cool white dimming.',
    description: 'Tuya smart recessed LED downlight with variable colour temperature (warm to cool white) and dimming. Suitable for new builds and renovations. App, voice and wall switch compatible.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-downlight/main.jpg'],
    tags: ['downlight', 'recessed', 'dimmable', 'colour temperature'],
    inStock: true,
  },
  {
    id: 'gw-t-light-sensor',
    slug: 'tuya-light-sensor',
    sku: 'GW-T-LSENSOR',
    name: 'Tuya Light Sensor',
    shortDesc: 'Lux-based light sensor for automation triggers.',
    description: 'Tuya WiFi light sensor measures ambient lux levels. Use as an automation trigger — turn lights on at dusk, close blinds in bright sunlight, or trigger scenes based on light levels.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-light-sensor/main.jpg'],
    tags: ['light sensor', 'lux', 'automation', 'trigger'],
    inStock: true,
  },
  {
    id: 'gw-a-pir-808wt',
    slug: 'tuya-wifi-pir-detector-808wt',
    sku: 'GW-A-WL-808WT',
    name: 'Tuya WiFi PIR Motion Detector WL-808WT',
    shortDesc: 'Wi-Fi PIR motion sensor — no hub required.',
    description: 'Tuya WiFi PIR motion detector. Works standalone over Wi-Fi — no hub or zigbee gateway needed. Triggers automations, sends app alerts, and integrates with smart home scenes.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['https://images.unsplash.com/photo-1557726087-3bf13f5a37e7?w=400&q=80'],
    tags: ['pir', 'motion sensor', 'wifi', 'security', 'alert'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-a-rf-pir-803w',
    slug: 'tuya-rf-433mhz-pir-detector',
    sku: 'GW-A-WL-803W',
    name: 'Tuya RF 433MHz PIR Motion Detector WL-803W',
    shortDesc: 'RF 433MHz PIR sensor — pairs with Tuya alarm hubs.',
    description: 'RF 433MHz PIR motion detector for use with Tuya-compatible alarm hubs and gateways. Battery-powered. Mounts in corners for wide-angle detection.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-rf-pir-803w/main.jpg'],
    tags: ['rf', '433mhz', 'pir', 'alarm', 'hub'],
    inStock: true,
  },
  {
    id: 'gw-a-presence-sensor-24ghz',
    slug: 'tuya-wifi-24ghz-human-presence-sensor',
    sku: 'GW-A-WL-RTCZ-03T',
    name: 'Tuya WiFi 2.4GHz Human Presence Sensor',
    shortDesc: 'mmWave radar presence sensor — detects stationary occupancy.',
    description: 'Next-gen mmWave 2.4GHz radar sensor that detects stationary human presence — not just movement. Perfect for automating lights in rooms where you sit still. Wi-Fi connected, no hub needed.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-presence-24ghz/main.jpg'],
    tags: ['presence sensor', 'mmwave', 'radar', 'stationary detection'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-a-presence-sensor-58ghz',
    slug: 'tuya-wifi-58ghz-human-presence-sensor',
    sku: 'GW-A-WL-RTCZ-05T',
    name: 'Tuya WiFi 5.8GHz Human Presence Sensor',
    shortDesc: '5.8GHz microwave presence sensor with luminance detection.',
    description: '5.8GHz microwave radar presence sensor. Detects stationary occupancy with high accuracy. Includes ambient luminance measurement for lux-based automations. Wi-Fi, no hub needed.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-presence-58ghz/main.jpg'],
    tags: ['presence sensor', '5.8ghz', 'microwave', 'lux', 'radar'],
    inStock: true,
  },
  {
    id: 'gw-a-zigbee-presence-24ghz',
    slug: 'tuya-zigbee-24ghz-presence-sensor',
    sku: 'GW-A-WL-RTCZ-03Z',
    name: 'Tuya Zigbee 2.4GHz Human Presence Sensor with Lux',
    shortDesc: 'Zigbee mmWave presence sensor with lux — pairs with Zigbee hub.',
    description: 'Zigbee 2.4GHz mmWave radar presence sensor with ambient light (lux) measurement. Requires Tuya Zigbee hub or Home Assistant with Zigbee coordinator. Ideal for local control and Home Assistant automations.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-zigbee-presence/main.jpg'],
    tags: ['zigbee', 'presence sensor', 'lux', 'home assistant'],
    inStock: true,
  },
  {
    id: 'gw-a-door-sensor-wifi',
    slug: 'tuya-wifi-door-window-sensor',
    sku: 'GW-A-WL-19JWT',
    name: 'Tuya WiFi Door/Window Magnetic Sensor',
    shortDesc: 'Wi-Fi door/window sensor — no hub required.',
    description: 'Tuya WiFi magnetic contact sensor for doors and windows. Triggers automations and push alerts when opened or closed. Works standalone over Wi-Fi — no hub needed.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80'],
    tags: ['door sensor', 'window sensor', 'magnetic', 'wifi', 'alert'],
    inStock: true,
  },
  {
    id: 'gw-a-door-sensor-zigbee',
    slug: 'tuya-zigbee-door-window-sensor',
    sku: 'GW-A-WL-19JWZ',
    name: 'Tuya Zigbee Door/Window Magnetic Sensor',
    shortDesc: 'Zigbee door/window contact sensor for hub-based systems.',
    description: 'Tuya Zigbee magnetic contact sensor. Pairs with Tuya Zigbee hub or Home Assistant Zigbee coordinator. Low power consumption, reliable local control.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-door-sensor-zigbee/main.jpg'],
    tags: ['door sensor', 'zigbee', 'home assistant', 'local control'],
    inStock: true,
  },
  {
    id: 'gw-a-vibration-sensor',
    slug: 'tuya-wifi-vibration-detector',
    sku: 'GW-A-WL-72WT',
    name: 'Tuya WiFi Vibration Detector WL-72WT',
    shortDesc: 'Detects vibration and shock — for safes, windows and vehicles.',
    description: 'Tuya WiFi vibration and shock detector. Alerts you to forced entry attempts on safes, windows, doors and vehicles. Adjustable sensitivity. No hub required.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-vibration/main.jpg'],
    tags: ['vibration', 'shock', 'safe', 'break-in', 'security'],
    inStock: true,
  },
  {
    id: 'gw-t-smoke-detector',
    slug: 'tuya-wifi-smart-smoke-detector',
    sku: 'GW-T-SMOKE',
    name: 'Tuya WiFi Smart Smoke Detector',
    shortDesc: 'Wi-Fi smoke alarm with app alerts and siren.',
    description: 'Tuya WiFi photoelectric smoke detector with 85dB siren and real-time push alerts to your phone. Test button, low battery alert and interconnect support. SANS 1431 compliant.',
    category: 'environmental',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-smoke-detector/main.jpg'],
    tags: ['smoke detector', 'fire alarm', 'safety', 'wifi'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-t-water-leak',
    slug: 'tuya-wifi-smart-water-leak-detector',
    sku: 'GW-T-WATER-LEAK',
    name: 'Tuya Wi-Fi Smart Water Leak Detector',
    shortDesc: 'Instant alerts when water is detected under appliances.',
    description: 'Tuya WiFi water leak detector. Place under washing machines, dishwashers, geysers and sinks. Sends push alerts the moment water is detected. No hub required.',
    category: 'environmental',
    brand: 'Tuya',
    price: 0,
    images: ['https://images.unsplash.com/photo-1548611716-b83e8c9e3eb0?w=400&q=80'],
    tags: ['water leak', 'flood', 'geyser', 'washing machine', 'alert'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-a-universal-remote',
    slug: 'tuya-universal-smart-remote-control',
    sku: 'GW-A-REMOTE',
    name: 'Tuya Universal Smart IR/RF Remote Control',
    shortDesc: 'Control TVs, ACs, fans and more from one app.',
    description: 'Tuya universal smart remote hub. Controls IR and RF devices — TVs, air conditioners, fans, set-top boxes and more. Learn mode for any remote. Integrates with scenes and voice assistants.',
    category: 'remote-control',
    brand: 'Tuya',
    price: 0,
    images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80'],
    tags: ['remote control', 'ir', 'rf', 'air conditioner', 'tv', 'universal'],
    inStock: true,
  },
  {
    id: 'gw-a-ir-rf-combo',
    slug: 'tuya-wifi-ir-rf-universal-remote',
    sku: 'GW-A-WL-IRF',
    name: 'Tuya WiFi IR+RF 2-in-1 Universal Remote WL-IRF',
    shortDesc: 'Combined IR and RF remote in a single compact unit.',
    description: 'Dual-protocol (IR + RF) universal remote controller. One device controls both infrared devices (TVs, ACs) and RF devices (fans, roller shutters). No hub needed.',
    category: 'remote-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-ir-rf/main.jpg'],
    tags: ['ir', 'rf', 'remote', 'air conditioner', 'roller shutter'],
    inStock: true,
  },
  {
    id: 'gw-a-remote-temp',
    slug: 'tuya-wifi-remote-control-with-temperature',
    sku: 'GW-A-WL-IRTP',
    name: 'Tuya WiFi Remote Control with Temperature Sensor WL-IRTP',
    shortDesc: 'IR remote hub with built-in temperature and humidity sensor.',
    description: 'IR universal remote with integrated temperature and humidity sensor. Automate your AC based on actual room temperature. No hub required.',
    category: 'remote-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-remote-temp/main.jpg'],
    tags: ['ir remote', 'temperature', 'humidity', 'ac automation'],
    inStock: true,
  },
  {
    id: 'gw-t-video-doorbell',
    slug: 'tuya-wifi-video-doorbell-alexa',
    sku: 'GW-T-DOORBELL',
    name: 'Tuya WiFi Video Doorbell with Alexa',
    shortDesc: 'HD video doorbell with two-way audio and motion alerts.',
    description: 'Tuya WiFi video doorbell with 1080p HD camera, two-way audio, motion detection alerts and night vision. Alexa and Google Home compatible. Local storage via micro-SD card.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-video-doorbell/main.jpg'],
    tags: ['doorbell', 'camera', 'video', 'two-way audio', 'security'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-a-video-doorbell-ml1t',
    slug: 'tuya-wifi-video-doorbell-ml1t',
    sku: 'GW-A-WL-ML1T',
    name: 'Tuya WiFi Video Doorbell WL-ML1T',
    shortDesc: 'Premium video doorbell with PIR and cloud/local storage.',
    description: 'Tuya WiFi 1080p video doorbell with PIR motion detection, two-way audio, night vision, and cloud or local (micro-SD) storage. Wide-angle lens. Weatherproof.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-video-doorbell/main.jpg'],
    tags: ['doorbell', 'camera', 'pir', 'weatherproof', 'security'],
    inStock: true,
  },
  {
    id: 'gw-t-garage-door',
    slug: 'tuya-wifi-smart-garage-door-opener',
    sku: 'GW-T-GARAGE',
    name: 'Tuya WiFi Smart Garage Door Controller',
    shortDesc: 'Open, close and monitor your garage door from anywhere.',
    description: 'Tuya WiFi garage door controller. Works with most existing garage motors. Open and close remotely, receive alerts when the door is left open, and set auto-close timers.',
    category: 'access-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-garage-door/main.jpg'],
    tags: ['garage door', 'motor', 'access control', 'remote'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-a-drawer-lock',
    slug: 'tuya-smart-drawer-lock-bt',
    sku: 'GW-A-LOCK-BT',
    name: 'Tuya Smart Drawer/Cabinet Lock (Bluetooth)',
    shortDesc: 'Bluetooth smart lock for drawers, cabinets and lockers.',
    description: 'Tuya Bluetooth smart lock for drawers, cabinets and lockers. App controlled. Access log included. Battery powered. Suitable for home, office and retail use.',
    category: 'access-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-drawer-lock/main.jpg'],
    tags: ['smart lock', 'cabinet', 'drawer', 'bluetooth'],
    inStock: true,
  },
  {
    id: 'gw-t-blinds-controller',
    slug: 'tuya-smart-blinds-controller',
    sku: 'GW-T-BLINDS',
    name: 'Tuya Smart Blinds/Curtain Controller',
    shortDesc: 'Automate existing roller blinds and venetian blinds.',
    description: 'Tuya smart motor controller for roller blinds and venetian blinds. App, voice and schedule control. Compatible with most existing blinds. Works with Alexa, Google Home and Home Assistant.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-blinds/main.jpg'],
    tags: ['blinds', 'curtains', 'motor', 'automation', 'roller shutter'],
    inStock: true,
  },
  {
    id: 'gw-t-curtain-opener',
    slug: 'tuya-smart-wifi-curtain-opener',
    sku: 'GW-T-CURTAIN-2PK',
    name: 'Tuya Smart WiFi Curtain Opener/Closer (2-Pack)',
    shortDesc: 'Motorise existing curtain rails — comes as a 2-pack.',
    description: 'Tuya WiFi curtain motor set (2-pack) for existing curtain rails. Retrofit installation — no rewiring. App, voice and schedule control. Works with Alexa, Google Home and Home Assistant.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-curtain/main.jpg'],
    tags: ['curtains', 'motor', '2-pack', 'retrofit', 'curtain rail'],
    inStock: true,
  },
  {
    id: 'gw-t-irrigation-4zone',
    slug: 'tuya-smart-wifi-irrigation-controller-4zone',
    sku: 'GW-T-IRRIGATION-4Z',
    name: 'Tuya Smart WiFi Irrigation Controller — 4 Zone (2nd Gen)',
    shortDesc: 'Automate up to 4 garden irrigation zones from your phone.',
    description: 'Tuya 2nd-gen WiFi irrigation controller with 4 independent zones. Schedule watering by zone, duration and frequency. App control, rain skip automation. Works with Alexa and Google Home.',
    category: 'water-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-irrigation/main.jpg'],
    tags: ['irrigation', 'garden', '4 zone', 'watering', 'outdoor'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-p-load-shedding-pack',
    slug: 'tuya-load-shedding-detector-pack',
    sku: 'GW-P-LSPACK',
    name: 'TUYA Load Shedding Detector Pack',
    shortDesc: 'SA-specific pack to detect and automate around load shedding.',
    description: 'South Africa-specific load shedding automation pack. Detects when power is cut and restored. Automate lights, geysers and devices to respond intelligently to load shedding schedules.',
    category: 'bundles',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-p-load-shedding/main.jpg'],
    tags: ['load shedding', 'eskom', 'automation', 'south africa', 'bundle'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-t-echo-pop',
    slug: 'amazon-echo-pop-cypress-green',
    sku: 'GW-T-ECHO-POP',
    name: 'Amazon Echo Pop — Cypress Green',
    shortDesc: 'Compact Alexa smart speaker. Control your Tuya devices by voice.',
    description: 'Amazon Echo Pop with Alexa. Compact smart speaker that pairs with all Tuya and Smartlife devices. Ask Alexa to control lights, switches, plugs and scenes by voice. Cypress Green colour.',
    category: 'voice-assistants',
    brand: 'Amazon Echo',
    price: 0,
    images: ['/images/products/gw-t-echo-pop/main.jpg'],
    tags: ['alexa', 'amazon echo', 'voice assistant', 'speaker'],
    inStock: true,
  },
  {
    id: 'gw-t-echo-dot-5',
    slug: 'amazon-echo-dot-5th-gen-deep-sea-blue',
    sku: 'GW-T-ECHO-DOT5',
    name: 'Amazon Echo Dot 5th Gen — Deep Sea Blue',
    shortDesc: 'Popular Alexa smart speaker with improved sound.',
    description: 'Amazon Echo Dot (5th Gen, 2022). Improved sound quality vs previous generation. Built-in Alexa for voice control of your smart home. Motion sensor for proximity automations. Deep Sea Blue.',
    category: 'voice-assistants',
    brand: 'Amazon Echo',
    price: 0,
    images: ['/images/products/gw-t-echo-dot5/main.jpg'],
    tags: ['alexa', 'echo dot', 'voice assistant', 'speaker', '5th gen'],
    inStock: true,
  },
  {
    id: 'gw-t-echo-show-5',
    slug: 'amazon-echo-show-5-3rd-gen-glacier-white',
    sku: 'GW-T-ECHO-SHOW5',
    name: 'Amazon Echo Show 5 (3rd Gen, 2023) — Glacier White',
    shortDesc: 'Smart display with Alexa, 2MP camera and video calling.',
    description: 'Amazon Echo Show 5 (3rd Gen, 2023). 5.5" touchscreen smart display with Alexa. 2MP camera for video calls, smart home dashboard, media playback and routines. Glacier White.',
    category: 'voice-assistants',
    brand: 'Amazon Echo',
    price: 0,
    images: ['/images/products/gw-t-echo-show5/main.jpg'],
    tags: ['alexa', 'echo show', 'smart display', 'video calls', '2023'],
    inStock: true,
  },
  {
    id: 'gw-t-nest-mini-2',
    slug: 'google-nest-mini-2-chalk',
    sku: 'GW-T-NEST-MINI2',
    name: 'Google Nest Mini (2nd Gen) — Chalk',
    shortDesc: 'Google Assistant smart speaker for voice control.',
    description: 'Google Nest Mini 2nd Gen. Wall-mountable smart speaker with Google Assistant. Control compatible smart home devices by voice. Stream music and answer questions. Chalk colour.',
    category: 'voice-assistants',
    brand: 'Google Nest',
    price: 0,
    images: ['/images/products/gw-t-nest-mini/main.jpg'],
    tags: ['google assistant', 'nest mini', 'voice assistant', 'speaker'],
    inStock: true,
  },
  {
    id: 'gw-10k-powerbank',
    slug: '10000mah-20w-powerbank-pd',
    sku: 'GW-PB-10K-20W',
    name: '10,000mAh 20W PD Power Bank',
    shortDesc: 'Fast-charge power bank — keep devices powered during load shedding.',
    description: '10,000mAh portable power bank with 20W Power Delivery (PD) fast charging. USB-C and USB-A outputs. Keep phones, tablets and smart home hubs powered during load shedding.',
    category: 'power-control',
    brand: 'GeeWiz',
    price: 0,
    images: ['/images/products/gw-powerbank/main.jpg'],
    tags: ['power bank', 'load shedding', 'fast charge', 'pd', '20w'],
    inStock: true,
  },

  // ─── TP-Link TAPO Products ─────────────────────────────────────────────────

  {
    id: 'tapo-s110e',
    slug: 'tapo-s110e-smart-switch-module',
    sku: 'TAPO-S110E',
    name: 'Tapo S110E Smart Switch Module',
    shortDesc: 'Dry/wet contact smart switch with energy monitoring, Bluetooth instant control and garage door integration.',
    description: 'The Tapo S110E Smart Switch Module supports Dry Contact, Wet Contact, and Garage Door Control modes. Track energy generation and usage, control remotely via the Tapo app, and set schedules. Features Relay Failure Protection, Zero-Control Protection, and instant Bluetooth control. Indoor use only, -20°C to 40°C. 6 months warranty.',
    category: 'power-control',
    brand: 'TP-Link TAPO',
    price: 458,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_S110E_UN_1.0_overview_01_normal_20250529132340y.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_S110E_UN_1.0_overview_02_normal_20250529132353h.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_S110E_UN_1.0_overview_03_normal_20250529132406y.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_S110E_UN_1.0_overview_04_normal_20250529132420m.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_S110E_UN_1.0_overview_05_normal_20250529132434k.jpg',
    ],
    tags: ['smart switch', 'energy monitoring', 'bluetooth', 'garage', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c113',
    slug: 'tapo-c113-indoor-outdoor-wifi-security-camera',
    sku: 'TAPO-C113',
    name: 'Tapo C113 Indoor/Outdoor Wi-Fi Security Camera',
    shortDesc: '2K 3MP camera with AI detection, color night vision, dual spotlights, two-way audio and IP65 weatherproofing.',
    description: 'The TP-Link Tapo C113 delivers sharp 2K 3MP video with color night vision powered by dual built-in spotlights. Features AI detection, two-way communication, IP65 weather resistance, and local storage via MicroSD (up to 512GB) plus cloud storage. Works with Google Home and Alexa. 6 months warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 765,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_C113_US_1.0_overview_normal_20250409023946g.png',
      'https://static.tp-link.com/upload/image-line/Tapo_C113_US_1.0_overview_01-2_normal_20250409024001i.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C113_US_1.0_overview_01-3_normal_20250409024013t.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C113_US_1.0_overview_02_normal_20250730053517u.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C113_US_1.0_overview_03_normal_20250422062120j.jpg',
    ],
    tags: ['camera', 'security', 'ai detection', '2k', 'outdoor', 'tapo'],
    inStock: true,
    featured: true,
  },
  {
    id: 'tapo-t110',
    slug: 'tapo-t110-smart-contact-sensor',
    sku: 'TAPO-T110',
    name: 'Tapo T110 Smart Door/Window Contact Sensor',
    shortDesc: 'Wireless 868 MHz contact sensor with 2-year battery life. Requires Tapo Hub. Ultra-compact design.',
    description: 'The Tapo T110 detects door and window openings instantly via 868/922 MHz wireless. Features a 2-year battery life (CR2032), LED indicator, and ultra-compact 61.4 x 37.5 x 12.3 mm body. Requires a Tapo Hub. Triggers automations and sends instant push notifications. 6 months warranty.',
    category: 'environmental',
    brand: 'TP-Link TAPO',
    price: 305,
    images: [
      'https://static.tp-link.com/upload/image-line/01_normal_20250115024454y.png',
      'https://static.tp-link.com/upload/image-line/02_normal_20240223065851p.jpg',
      'https://static.tp-link.com/upload/image-line/03_normal_20240223070834n.jpg',
      'https://static.tp-link.com/upload/image-line/04_normal_20240223070901h.jpg',
      'https://static.tp-link.com/upload/image-line/05_normal_20240223070919j.jpg',
    ],
    tags: ['contact sensor', 'door sensor', 'window sensor', '868mhz', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-d205',
    slug: 'tapo-d205-2k-battery-video-doorbell',
    sku: 'TAPO-D205',
    name: 'Tapo D205 2K Battery Video Doorbell',
    shortDesc: '2K video doorbell with 160° wide FOV, two-way audio, IP54 weatherproofing and solar panel support.',
    description: 'The Tapo D205 delivers 2K 3MP live view with a massive 160° diagonal FOV and 10x digital zoom. Features two-way audio, accurate motion alerts, local MicroSD (up to 512GB) and cloud storage, and solar panel support. Battery powered, IP54 weatherproof. Quick response so you never miss a visitor. 6 months warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 1225,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_D205_UN_1.0_overview_01-1_normal_20250708062927b.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_D205_UN_1.0_overview_01-2_normal_20250708062927j.jpg',
      'https://static.tp-link.com/upload/image-line/02_normal_20250708063055j.jpg',
      'https://static.tp-link.com/upload/image-line/03_normal_20250708063119s.jpg',
      'https://static.tp-link.com/upload/image-line/04_compressed_normal_20250708063347b.jpg',
    ],
    tags: ['doorbell', 'camera', 'video doorbell', '2k', 'battery', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-d210',
    slug: 'tapo-d210-2k-battery-video-doorbell-camera',
    sku: 'TAPO-D210',
    name: 'Tapo D210 2K Battery Video Doorbell Camera',
    shortDesc: '2K doorbell with 160° FOV, full-color night vision, 6-month battery life and two-way audio.',
    description: 'The Tapo D210 features 2K 3MP ultra-wide 160° diagonal FOV with 10x digital zoom. Full-color night vision, two-way audio, 6-month battery life, smarter AI detection, and local/cloud storage. No subscription required. Works with Alexa and Google Home. 6 months warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 1685,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_D210_EU_2.0_Overview_01_normal_20250922080155w.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_D210_EU_2.0_Overview_02_normal_20250922080207j.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_D210_EU_2.0_Overview_03_normal_20250922080220l.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_D210_EU_2.0_Overview_04_normal_20250922080255h.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_D210_EU_2.0_Overview_05_normal_20250922080312j.jpg',
    ],
    tags: ['doorbell', 'camera', '2k', 'color night vision', 'battery', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c260',
    slug: 'tapo-c260-4k-pan-tilt-ai-indoor-camera',
    sku: 'TAPO-C260',
    name: 'Tapo C260 4K Pan/Tilt AI Indoor Camera',
    shortDesc: '4K 8MP pan/tilt camera with 360°/116° range, human face recognition and privacy mode.',
    description: 'The Tapo C260 records ultra-sharp 4K 8MP video with 360° horizontal and 116° vertical pan/tilt range. Features human face recognition, enhanced 40ft night vision, smart AI detection, physical privacy mode, customizable block zones, sound and light alarm, two-way audio, and MicroSD storage up to 512GB. 6 months warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 1532,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_C260_UN_1.0_overview_01_normal_20250314011954p.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C260_UN_1.0_overview_02_normal_20250314012013j.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C260_UN_1.0_overview_03_normal_20250314012030i.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C260_UN_1.0_overview_04_normal_20250428034821q.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C260_UN_1.0_overview_05_normal_20250314012106n.jpg',
    ],
    tags: ['camera', 'pan tilt', '4k', 'ai detection', 'face recognition', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c530ws',
    slug: 'tapo-c530ws-outdoor-3k-pan-tilt-camera',
    sku: 'TAPO-C530WS',
    name: 'Tapo C530WS Outdoor 3K Pan/Tilt Security Camera',
    shortDesc: '3K 5MP outdoor pan/tilt with 360° coverage, Starlight color night vision, IP66 and AI detection.',
    description: 'The Tapo C530WS delivers 3K 5MP outdoor security with Starlight Color Night Vision for vibrant footage in low light. Features 360° all-round protection, comprehensive AI detection, flexible Wi-Fi/wired connections, IP66 weatherproofing, customizable sound and light alarm, and local/cloud storage. Two-way audio. 6 months warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 1762,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_C530WS_EU_2.0_overview_01_normal_20241031071947c.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C530WS_EU_2.0_overview_02_normal_20241031071957y.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C530WS_EU_2.0_overview_03_normal_20241031072009c.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C530WS_EU_2.0_overview_04_normal_20241031072020g.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C530WS_EU_2.0_overview_05_normal_20241031072034c.jpg',
    ],
    tags: ['camera', 'outdoor', '3k', 'pan tilt', 'starlight', 'ip66', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c660-kit',
    slug: 'tapo-c660-kit-solar-4k-pan-tilt-security-kit',
    sku: 'TAPO-C660-KIT',
    name: 'Tapo C660 KIT Solar-Powered 4K Pan/Tilt Security Kit',
    shortDesc: 'Solar-powered 4K pan/tilt kit with 360° AI tracking, 10000 mAh battery, dual spotlights and IP65.',
    description: 'The Tapo C660 KIT is a solar-powered 4K 8MP pan/tilt security camera with 18x digital zoom and 360° AI tracking. Includes solar panel for continuous charging. Features Starlight Color Night Vision, 2 built-in spotlights, two-way audio with noise cancellation, 10000 mAh rechargeable battery, local MicroSD and cloud storage, IP65. 6 months warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 3832,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_C660_KIT_EU_1.0_overview_01_normal_20250408025139s.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C660_KIT_EU_1.0_overview_04_normal_20250408025214t.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C660_KIT_EU_1.0_overview_08_normal_20250408025409t.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C660_KIT_EU_1.0_overview_09_normal_20250408025426b.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C660_KIT_EU_1.0_overview_10_normal_20250408025441c.jpg',
    ],
    tags: ['camera', 'solar', '4k', 'pan tilt', 'ai tracking', 'battery', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-l535e',
    slug: 'tapo-l535e-smart-wifi-bulb-e27-multicolor',
    sku: 'TAPO-L535E',
    name: 'Tapo L535E Smart Wi-Fi Multicolor Bulb (E27)',
    shortDesc: '1055-lumen E27 smart bulb with 16M colors, 2500K–6500K color temperature and voice control.',
    description: 'The Tapo L535E E27 smart bulb delivers 1055 lumens (75W equivalent) with a full spectrum of 16 million colors and adjustable color temperature from 2500K to 6500K. Control via app, schedule, or voice (Google Home, Amazon Alexa). Features dimming, scheduling, and energy-efficient operation with a 25,000-hour lifespan.',
    category: 'lighting',
    brand: 'TP-Link TAPO',
    price: 305,
    images: [
      'https://static.tp-link.com/upload/image-line/Overview_01_normal_20230905062436h.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_02_normal_20230905062448r.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_03_normal_20230905062502s.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_04_normal_20230905062515z.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_05_normal_20230905062527b.jpg',
    ],
    tags: ['bulb', 'e27', 'smart bulb', 'rgb', 'multicolor', 'tapo'],
    inStock: true,
    featured: true,
  },
  {
    id: 'tapo-l535b',
    slug: 'tapo-l535b-smart-wifi-bulb-b22-multicolor',
    sku: 'TAPO-L535B',
    name: 'Tapo L535B Smart Wi-Fi Multicolor Bulb (B22)',
    shortDesc: '1055-lumen B22 bayonet smart bulb with 16M colors, 2500K–6500K temperature and app/voice control.',
    description: 'The Tapo L535B B22 bayonet smart bulb delivers 1055 lumens (75W equivalent) with 16 million colors and adjustable color temperature (2500K to 6500K). 220° wide beam angle, 25,000-hour lifespan. Control via Tapo app or voice (Alexa, Google Home). Ideal for South African bayonet fittings.',
    category: 'lighting',
    brand: 'TP-Link TAPO',
    price: 305,
    images: [
      'https://static.tp-link.com/upload/image-line/Overview_01_normal_20231023014744l.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_02_normal_20231023014757x.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_03_normal_20231023014808l.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_04_normal_20231023014826t.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_05_normal_20231023014844i.jpg',
    ],
    tags: ['bulb', 'b22', 'bayonet', 'smart bulb', 'rgb', 'multicolor', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c425-kit',
    slug: 'tapo-c425-kit-solar-security-camera-kit',
    sku: 'TAPO-C425-KIT',
    name: 'Tapo C425 KIT Solar-Powered 2K Wire-Free Security Camera Kit',
    shortDesc: 'Solar 2K QHD wire-free kit with AI detection, color night vision and IP66 weatherproofing.',
    description: 'The Tapo C425 KIT is a solar-powered, wire-free 2K QHD security camera system with color night vision and free AI detection for people, pets, and vehicles. IP66 weatherproof. Included solar panel provides uninterrupted power with just 45 minutes of sunlight daily. Local storage up to 512GB, optional cloud storage. Easy wireless installation.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 3142,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo-C425-KIT_EU_1.2_01_normal_20240507101632u.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo-C425-KIT_EU_1.2_02_normal_20240507102714y.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo-C425-KIT_EU_1.2_03_normal_20240507102906j.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo-C425-KIT_EU_1.2_04_normal_20240507102920i.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo-C425-KIT_EU_1.2_05_normal_20240507102939b.jpg',
    ],
    tags: ['camera', 'solar', '2k', 'wire-free', 'ai detection', 'ip66', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-t100',
    slug: 'tapo-t100-smart-motion-sensor',
    sku: 'TAPO-T100',
    name: 'Tapo T100 Smart Motion Sensor',
    shortDesc: '868 MHz motion sensor with 120° / 7m range. Requires Tapo Hub. Battery included.',
    description: 'The Tapo T100 Smart Motion Sensor detects motion up to 7 metres with a 120° field of view. Operates on 868 MHz and requires a Tapo Hub. Long battery life, easy installation, and seamless integration with the Tapo smart app for automations and alerts. Battery included. 1 year warranty.',
    category: 'environmental',
    brand: 'TP-Link TAPO',
    price: 397,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_T100_EU_1.2_overview_1_normal_20250115023545v.png',
      'https://static.tp-link.com/upload/image-line/Tapo_T100_EU_1.2_overview_normal_20250115023814s.png',
      'https://static.tp-link.com/upload/image-line/Tapo_T100_03_normal_20240118032620c.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_T100_04_normal_20240118032637q.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_T100_05_normal_20240118032659t.jpg',
    ],
    tags: ['motion sensor', 'pir', '868mhz', 'security', 'hub required', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c425',
    slug: 'tapo-c425-wire-free-2k-security-camera',
    sku: 'TAPO-C425',
    name: 'Tapo C425 Smart Wire-Free 2K Security Camera',
    shortDesc: '2K wire-free camera with 365-day battery, AI detection, magnetic base, color night vision and IP66.',
    description: 'The Tapo C425 is a 100% wire-free 2K QHD (2560×1440) security camera with an impressive 365-day battery life. Features smart AI detection for motion, people, pets, and vehicles; color night vision; sound and light alarm; magnetic base; two-way audio; and local MicroSD storage up to 512GB. IP66 weatherproof. Works with Alexa and Google Home. 1 year warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 2758,
    images: [
      'https://static.tp-link.com/upload/image-line/01_normal_20231027074200e.jpg',
      'https://static.tp-link.com/upload/image-line/02_normal_20231027074225z.jpg',
      'https://static.tp-link.com/upload/image-line/03_normal_20231027074252q.jpg',
      'https://static.tp-link.com/upload/image-line/04_normal_20230829073506h.jpg',
      'https://static.tp-link.com/upload/image-line/05_normal_20230829073600z.jpg',
    ],
    tags: ['camera', 'wire-free', '2k', 'battery', 'ai detection', 'ip66', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-l530b',
    slug: 'tapo-l530b-smart-wifi-multicolor-bulb-b22',
    sku: 'TAPO-L530B',
    name: 'Tapo L530B Smart Wi-Fi Multicolor Bulb (B22)',
    shortDesc: '806-lumen B22 smart bulb with 16M colors, stepless dimming, scheduling and away mode.',
    description: 'The Tapo L530B B22 bayonet smart bulb offers 16 million customizable colors with stepless dimming up to 806 lumens. Features scheduling, timers, away mode, and voice control via Amazon Alexa and Google Assistant. Remote control through the Tapo app. 25,000-hour lifespan. Ideal for South African B22 bayonet fittings.',
    category: 'lighting',
    brand: 'TP-Link TAPO',
    price: 259,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_L530B(4-Pack)2.0-1000x1000_normal_20221020061315k.jpg',
      'https://static.tp-link.com/upload/image-line/02_normal_20221020061216q.jpg',
      'https://static.tp-link.com/upload/image-line/03_normal_20221020061217y.jpg',
      'https://static.tp-link.com/upload/image-line/04_normal_20221020061218w.jpg',
      'https://static.tp-link.com/upload/image-line/05_normal_20221020061218u.jpg',
    ],
    tags: ['bulb', 'b22', 'bayonet', 'smart bulb', 'rgb', 'multicolor', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-h100',
    slug: 'tapo-h100-smart-hub-with-chime',
    sku: 'TAPO-H100',
    name: 'Tapo H100 Smart Hub with Chime',
    shortDesc: 'Smart hub connecting up to 64 Tapo sensors and devices via long-range low-power wireless.',
    description: 'The Tapo H100 Smart Hub with Chime is the heart of a Tapo smart home sensor ecosystem. Connects up to 64 sub-devices using a reliable long-range, low-power wireless protocol for extended standby times. Built-in chime alerts you to doorbell and sensor events. Easy setup via the Tapo app. 1 year warranty.',
    category: 'voice-assistants',
    brand: 'TP-Link TAPO',
    price: 535,
    images: [
      'https://static.tp-link.com/upload/image-line/Overview_normal_20250115023035g.png',
      'https://static.tp-link.com/upload/image-line/Overview_02_normal_20240711085139d.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_03_normal_20240711085149a.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_04_normal_20240711085159q.jpg',
      'https://static.tp-link.com/upload/image-line/Overview_05_normal_20240711085212e.jpg',
    ],
    tags: ['hub', 'gateway', 'smart home', 'tapo', 'sensors'],
    inStock: true,
    featured: true,
  },
  {
    id: 'tapo-c500',
    slug: 'tapo-c500-outdoor-pan-tilt-security-camera',
    sku: 'TAPO-C500',
    name: 'Tapo C500 Outdoor Pan/Tilt Security Wi-Fi Camera',
    shortDesc: 'Outdoor 360° pan/tilt camera with 1080p Starlight night vision, built-in siren and IP66.',
    description: 'The Tapo C500 protects your property with 360° rotation, sharp 1080p Starlight night vision, and accurate person detection. Deter intruders with the built-in siren and spotlight. Flexible mounting options for easy installation. Secure local MicroSD and cloud storage. Works with Alexa and Google Home. IP66. 1 year warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 1302,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_C500_EU_2.0_overview_2406_English_01-1_normal_20240620080043d.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C500_EU_2.0_overview_2406_English_01-2_normal_20240620080054p.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C500_EU_2.0_overview_2406_English_01-3_normal_20240620080105b.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C500_EU_2.0_overview_2406_English_01-4_normal_20240620080121h.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C500_EU_2.0_overview_2406_English_02_normal_20240620080141y.jpg',
    ],
    tags: ['camera', 'outdoor', 'pan tilt', '1080p', 'siren', 'ip66', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c210',
    slug: 'tapo-c210-indoor-pan-tilt-security-camera',
    sku: 'TAPO-C210',
    name: 'Tapo C210 Indoor Pan/Tilt Home Security Camera',
    shortDesc: '3MP indoor pan/tilt camera with wide-area coverage, night vision, motion alerts and two-way audio.',
    description: 'The Tapo C210 Wi-Fi camera provides sharp 3MP high-definition video with pan/tilt for wide-area coverage. Features 30ft night vision, motion detection with instant alerts, two-way audio, and voice control. Stores footage locally (MicroSD) or in the cloud. Easy setup via the Tapo app. 1 year warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 704,
    images: [
      'https://static.tp-link.com/upload/image-line/01_normal_20230524004739b.jpg',
      'https://static.tp-link.com/upload/image-line/03_normal_20230524004802a.jpg',
      'https://static.tp-link.com/upload/image-line/04_normal_20230524004834e.jpg',
      'https://static.tp-link.com/upload/image-line/05_normal_20230524004850p.jpg',
      'https://static.tp-link.com/upload/image-line/06_normal_20230524004908u.jpg',
    ],
    tags: ['camera', 'indoor', 'pan tilt', '3mp', 'night vision', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c325wb',
    slug: 'tapo-c325wb-outdoor-colorpro-security-camera',
    sku: 'TAPO-C325WB',
    name: 'Tapo C325WB Outdoor Security Wi-Fi Camera',
    shortDesc: '2688×1520 outdoor camera with ColorPro Night Vision, two built-in spotlights and AI detection.',
    description: 'The Tapo C325WB outdoor camera features a large 1/1.79" sensor and F1.0 aperture for stunning ColorPro Night Vision even in near darkness, powered by 2 built-in spotlights. Captures 2688×1520 resolution video with smart AI detection. Weatherproof and reliable. Includes power adapter and mounting hardware. 1 year warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 2682,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_C325WB(US)_1.0-CMYK-low_normal_20230417103921d.png',
      'https://static.tp-link.com/upload/image-line/01_normal_20230417103144y.jpg',
      'https://static.tp-link.com/upload/image-line/02_normal_20230417103216h.jpg',
      'https://static.tp-link.com/upload/image-line/03_normal_20230417103356u.jpg',
      'https://static.tp-link.com/upload/image-line/04_normal_20230417103322k.jpg',
    ],
    tags: ['camera', 'outdoor', 'color night vision', 'spotlight', 'ai', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c110',
    slug: 'tapo-c110-home-security-wifi-camera',
    sku: 'TAPO-C110',
    name: 'Tapo C110 Home Security Wi-Fi Camera',
    shortDesc: '3MP indoor security camera with 30ft night vision, motion detection and two-way audio.',
    description: 'The Tapo C110 provides sharp 3MP (2304×1296) video with 30ft infrared night vision. Motion detection sends instant alerts to your phone. Two-way audio for real-time communication. Local MicroSD and cloud storage. Simple setup via the Tapo app. Compatible with Alexa and Google Home. 1 year warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 704,
    images: [
      'https://static.tp-link.com/Tapo_c100-overview_normal_1616655163753g.jpg',
      'https://static.tp-link.com/Tapo_c100-overview3_normal_1616655194487p.jpg',
      'https://static.tp-link.com/Tapo_c100-overview4_normal_1616655205620g.jpg',
      'https://static.tp-link.com/Tapo_c100-overview2_normal_1616655225654y.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C110(US)3.0-175x145x64mm-7022514851_normal_20260113192344q.png',
    ],
    tags: ['camera', 'indoor', '3mp', 'night vision', 'security', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c510w',
    slug: 'tapo-c510w-outdoor-pan-tilt-security-camera',
    sku: 'TAPO-C510W',
    name: 'Tapo C510W Outdoor Pan/Tilt Security Wi-Fi Camera',
    shortDesc: 'Outdoor 360° pan/tilt camera with night vision, motion tracking, two-way audio and weather protection.',
    description: 'The Tapo C510W defends your outdoors with 360° rotation, sharp night vision, and motion tracking. Two-way audio and remote control let you see, hear, and speak to visitors from your smartphone. Stores footage locally on MicroSD or in the cloud. Works with Alexa and Google Home. 1 year warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 1225,
    images: [
      'https://static.tp-link.com/upload/image-line/Tapo_C510W_EU_2.0_overview_2406_English_01-1_normal_20240805085211p.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C510W_EU_2.0_overview_2406_English_01-2_normal_20240805085221o.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C510W_EU_2.0_overview_2406_English_01-3_normal_20240805085230m.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C510W_EU_2.0_overview_2406_English_01-4_normal_20240805085242s.jpg',
      'https://static.tp-link.com/upload/image-line/Tapo_C510W_EU_2.0_overview_2406_English_02_normal_20240805085256h.jpg',
    ],
    tags: ['camera', 'outdoor', 'pan tilt', 'night vision', 'motion tracking', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-c310',
    slug: 'tapo-c310-outdoor-security-wifi-camera',
    sku: 'TAPO-C310',
    name: 'Tapo C310 Outdoor Security Wi-Fi Camera',
    shortDesc: 'Outdoor 3MP camera with 30m night vision, two-way audio, motion detection and weatherproof design.',
    description: 'The Tapo C310 outdoor camera captures 3MP (2304×1296) video with 30m 850nm infrared night vision. Two-way audio with built-in microphone and speaker. Motion detection with instant alerts. H.264 compression. Wireless rates up to 150 Mbps. Easy installation. Compatible with Alexa and Google Home. 1 year warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 1072,
    images: [
      'https://static.tp-link.com/1_normal_1599194402144s.jpg',
      'https://static.tp-link.com/2_normal_1599194417653c.jpg',
      'https://static.tp-link.com/3_normal_1599194429663y.jpg',
      'https://static.tp-link.com/4_normal_1599194441148o.jpg',
    ],
    tags: ['camera', 'outdoor', '3mp', 'night vision', 'weatherproof', 'tapo'],
    inStock: true,
  },
  {
    id: 'tapo-p110',
    slug: 'tapo-p110-mini-smart-wifi-socket',
    sku: 'TAPO-P110',
    name: 'Tapo P110 Mini Smart Wi-Fi Socket with Energy Monitoring',
    shortDesc: 'Compact smart plug with energy monitoring, remote access, voice control and real-time power tracking.',
    description: 'The Tapo P110 Mini Smart Wi-Fi Socket tracks your device energy usage in real time. Set electricity rates to forecast your bill. Its compact design leaves adjacent outlets unblocked. Control by voice via Alexa or Google Assistant, or remotely via the Tapo app with scheduling and automation. 2 year warranty.',
    category: 'power-control',
    brand: 'TP-Link TAPO',
    price: 305,
    images: [
      'https://static.tp-link.com/upload/image-line/01_normal_20230901075712f.jpg',
      'https://static.tp-link.com/upload/image-line/02_normal_20230901075724y.jpg',
      'https://static.tp-link.com/upload/image-line/03_normal_20230901075735q.jpg',
      'https://static.tp-link.com/upload/image-line/04_normal_20230901075745y.jpg',
      'https://static.tp-link.com/upload/image-line/05_normal_20230901075756l.jpg',
    ],
    tags: ['smart plug', 'energy monitoring', 'mini', 'socket', 'tapo'],
    inStock: true,
    featured: true,
  },
  {
    id: 'tapo-c200',
    slug: 'tapo-c200-indoor-pan-tilt-home-security-camera',
    sku: 'TAPO-C200',
    name: 'Tapo C200 1080P Indoor Pan/Tilt Home Security Camera',
    shortDesc: '1080P indoor camera with 360°/114° pan/tilt, 30ft night vision, motion detection and two-way audio.',
    description: 'The Tapo C200 captures crystal-clear 1080P video with 360° horizontal and 114° vertical pan/tilt coverage. Advanced 30ft night vision, motion detection with instant push alerts, sound and light alarm to deter intruders, and two-way audio for real-time communication. Easy setup, local and cloud storage. 1 year warranty.',
    category: 'security',
    brand: 'TP-Link TAPO',
    price: 704,
    images: [
      'https://static.tp-link.com/upload/image-line/01_normal_20230817224004g.jpg',
      'https://static.tp-link.com/upload/image-line/03_normal_20230817224214m.jpg',
      'https://static.tp-link.com/upload/image-line/04_normal_20230817224556m.jpg',
      'https://static.tp-link.com/upload/image-line/05_normal_20230817224635c.jpg',
      'https://static.tp-link.com/upload/image-line/06_normal_20230817224714r.jpg',
    ],
    tags: ['camera', 'indoor', 'pan tilt', '1080p', 'night vision', 'tapo'],
    inStock: true,
    featured: true,
  },

  // ─── TP-Link Deco Mesh Wi-Fi Systems ───────────────────────────────────────

  {
    id: 'deco-m4-3-pack',
    slug: 'deco-m4-3-pack-ac1200-mesh-wifi',
    sku: 'DECO-M4-3-PACK',
    name: 'TP-Link Deco M4 AC1200 Whole Home Mesh Wi-Fi System (3-Pack)',
    shortDesc: 'AC1200 Wi-Fi 5 mesh system covers 3–5 bedroom homes. Dual-band with Gigabit ports and parental controls.',
    description: 'The Deco M4 (3-pack) creates a seamless mesh network covering large homes (3–5 bedrooms). Dual-band Wi-Fi 5 with up to 1167 Mbps (5GHz: 867 + 2.4GHz: 300 Mbps). Optional Ethernet backhaul, MU-MIMO, beamforming, SPI firewall, access control, parental controls, QoS, and 2x Gigabit ports per unit. Manage via the Deco app.',
    category: 'networking',
    brand: 'TP-Link Deco',
    price: 2758,
    images: [
      'https://api.esquire.co.za/Resources/Images/Products/DECO-M4-3-PACK-1.jpg',
    ],
    tags: ['mesh wifi', 'deco', 'ac1200', 'wifi 5', '3-pack', 'whole home'],
    inStock: true,
    featured: true,
  },
  {
    id: 'deco-m5-1-pack',
    slug: 'deco-m5-1-pack-ac1300-mesh-wifi',
    sku: 'DECO-M5-1-PACK',
    name: 'TP-Link Deco M5 AC1300 Whole Home Mesh Wi-Fi System (1-Pack)',
    shortDesc: 'Single AC1300 Deco M5 mesh unit. Expand your existing Deco system or start coverage in one room.',
    description: 'Deco M5 uses mesh technology to cover your home in powerful Wi-Fi. AC1300 dual-band (5GHz: 867 + 2.4GHz: 400 Mbps). Works with other M5 units for whole-home coverage. Easy setup via the Deco app. Ideal as a standalone unit or to expand an existing Deco M5 network. 2 year warranty.',
    category: 'networking',
    brand: 'TP-Link Deco',
    price: 1685,
    images: [
      'https://www.xyz.co.za/ProdImg/DECO-M5-1-PACKcover3.jpg',
    ],
    tags: ['mesh wifi', 'deco', 'ac1300', 'wifi 5', '1-pack'],
    inStock: true,
  },
  {
    id: 'deco-m5-2-pack',
    slug: 'deco-m5-2-pack-ac1300-mesh-wifi',
    sku: 'DECO-M5-2-PACK',
    name: 'TP-Link Deco M5 AC1300 Whole Home Mesh Wi-Fi System (2-Pack)',
    shortDesc: 'AC1300 mesh Wi-Fi 2-pack covers up to 3,800 sq ft for 100+ devices. Simple Deco app setup.',
    description: 'The Deco M5 (2-pack) AC1300 Whole Home Mesh Wi-Fi System provides seamless coverage up to 3,800 sq ft, eliminating dead zones for over 100 devices. Advanced mesh technology, unified network name, and smooth roaming. Parental controls, two Gigabit ports per unit, HomeShield security, and easy setup via the Deco app. 2 year warranty.',
    category: 'networking',
    brand: 'TP-Link Deco',
    price: 3985,
    images: [
      'https://api.esquire.co.za/Resources/Images/Products/DECO-M5-2-PACKmain3.jpg',
    ],
    tags: ['mesh wifi', 'deco', 'ac1300', 'wifi 5', '2-pack', 'whole home'],
    inStock: true,
  },
  {
    id: 'deco-m4-2-pack',
    slug: 'deco-m4-2-pack-ac1200-mesh-wifi',
    sku: 'DECO-M4-2-PACK',
    name: 'TP-Link Deco M4 AC1200 Whole Home Mesh Wi-Fi System (2-Pack)',
    shortDesc: 'AC1200 mesh Wi-Fi 2-pack eliminates dead zones, supports 100+ devices with Gigabit ports.',
    description: 'The Deco M4 (2-pack) provides seamless AC1200 dual-band mesh coverage, eliminating weak signal areas with a unified network name. Fast speeds up to 1167 Mbps, supports 100+ devices, smooth roaming, parental controls, two Gigabit ports per unit, and easy Deco app setup. 2 year warranty.',
    category: 'networking',
    brand: 'TP-Link Deco',
    price: 2145,
    images: [
      'https://api.esquire.co.za/Resources/Images/Products/DECO-M4-2-PACKMain3.jpg',
    ],
    tags: ['mesh wifi', 'deco', 'ac1200', 'wifi 5', '2-pack'],
    inStock: true,
  },
  {
    id: 'deco-be25-3-pack',
    slug: 'deco-be25-3-pack-wifi-7-be3600-mesh',
    sku: 'DECO-BE25-3-PACK',
    name: 'TP-Link Deco BE25 BE3600 Wi-Fi 7 Mesh System (3-Pack)',
    shortDesc: 'Wi-Fi 7 BE3600 mesh 3-pack with 2.5Gbps ports, 2882+688 Mbps dual-band speeds and AI-driven mesh.',
    description: 'The Deco BE25 (3-pack) delivers blazing BE3600 Wi-Fi 7 speeds: 5GHz 2882 Mbps + 2.4GHz 688 Mbps. Features AI-driven mesh optimisation, 4 high-performance internal antennas, 2x 2.5Gbps ports per unit, Multi-Link Operation (MLO), 4K-QAM modulation, OFDMA for 150+ devices, and WPA3 security. Router/AP modes. 6 months warranty.',
    category: 'networking',
    brand: 'TP-Link Deco',
    price: 7205,
    images: [
      'https://api.esquire.co.za/Resources/Images/Products/overview_06_normal_20240522060247h.jpg',
    ],
    tags: ['mesh wifi', 'deco', 'wifi 7', 'be3600', '3-pack', '2.5gbps'],
    inStock: true,
  },
  {
    id: 'deco-x10-3-pack',
    slug: 'deco-x10-3-pack-ax1500-wifi-6-mesh',
    sku: 'DECO-X10-3-PACK',
    name: 'TP-Link Deco X10 AX1500 Wi-Fi 6 Mesh System (3-Pack)',
    shortDesc: 'Wi-Fi 6 AX1500 mesh 3-pack with 1,201+300 Mbps dual-band speeds, OFDMA and parental controls.',
    description: 'The Deco X10 (3-pack) brings Wi-Fi 6 to your whole home. AX1500 dual-band speeds: 5GHz 1201 Mbps (802.11ax) + 2.4GHz 300 Mbps. OFDMA, MU-MIMO, beamforming, 4 streams. SPI firewall, access control, parental controls, QoS, and 2x Gigabit ports per unit. Router and AP modes. 6 months warranty.',
    category: 'networking',
    brand: 'TP-Link Deco',
    price: 3602,
    images: [
      'https://api.esquire.co.za/Resources/Images/Products/Deco_X10_Overview_04_normal_20230724014738s.jpg',
    ],
    tags: ['mesh wifi', 'deco', 'wifi 6', 'ax1500', '3-pack', 'ofdma'],
    inStock: true,
  },
  {
    id: 'deco-be25-2-pack',
    slug: 'deco-be25-2-pack-wifi-7-be3600-mesh',
    sku: 'DECO-BE25-2-PACK',
    name: 'TP-Link Deco BE25 BE3600 Wi-Fi 7 Mesh System (2-Pack)',
    shortDesc: 'Wi-Fi 7 BE3600 mesh 2-pack with MLO, 4K-QAM, 2.5Gbps ports and 150+ device support.',
    description: 'The Deco BE25 (2-pack) delivers dual-band Wi-Fi 7 at BE3600 speeds: 5GHz 2882 Mbps + 2.4GHz 688 Mbps. Features Multi-Link Operation (MLO), 4K-QAM, OFDMA for 150+ devices, 2x 2.5Gbps ports per unit, VPN server/client support, HomeShield security, and WPA3. Router/AP modes. 6 months warranty.',
    category: 'networking',
    brand: 'TP-Link Deco',
    price: 5058,
    images: [
      'https://api.esquire.co.za/Resources/Images/Products/DECO-1.png',
    ],
    tags: ['mesh wifi', 'deco', 'wifi 7', 'be3600', '2-pack', 'mlo'],
    inStock: true,
  },
  {
    id: 'deco-x50-outdoor',
    slug: 'deco-x50-outdoor-ax3000-outdoor-indoor-mesh-wifi-6',
    sku: 'DECO-X50-OUTDOOR',
    name: 'TP-Link Deco X50-Outdoor AX3000 Outdoor/Indoor Mesh Wi-Fi 6',
    shortDesc: 'IP65-rated outdoor/indoor mesh Wi-Fi 6 unit with PoE, 5GHz 2402 Mbps and pole/wall mounting.',
    description: 'The Deco X50-Outdoor is a weatherproof IP65 outdoor mesh Wi-Fi 6 unit delivering AX3000 speeds: 5GHz 2402 + 2.4GHz 574 Mbps. Features 2x Gigabit ports (WAN/LAN auto-sensing), PoE and AC power supply, OFDMA, MU-MIMO, 1024-QAM, WPA3, and multi-scenario mounting (pole, wall, tabletop). Works with Deco app, Alexa and Google Home.',
    category: 'networking',
    brand: 'TP-Link Deco',
    price: 2912,
    images: [
      'https://api.esquire.co.za/Resources/Images/Products/05_normal_20221028065959z.jpg',
    ],
    tags: ['mesh wifi', 'deco', 'wifi 6', 'ax3000', 'outdoor', 'ip65', 'poe'],
    inStock: true,
  },
  {
    id: 'deco-x55-3-pack',
    slug: 'deco-x55-3-pack-ax3000-wifi-6-mesh',
    sku: 'DECO-X55-3-PACK',
    name: 'TP-Link Deco X55 AX3000 Whole Home Mesh Wi-Fi 6 System (3-Pack)',
    shortDesc: 'AX3000 Wi-Fi 6 mesh 3-pack supporting 150+ devices with fast, reliable whole-home coverage.',
    description: 'The Deco X55 (3-pack) delivers superior AX3000 Wi-Fi 6 coverage for your entire home. Advanced Wi-Fi 6 technology ensures faster speeds, increased capacity, and better efficiency for 150+ simultaneous devices. Easy setup and management via the Deco app. HomeShield security, parental controls, and seamless roaming. 2 year warranty.',
    category: 'networking',
    brand: 'TP-Link Deco',
    price: 5058,
    images: [
      'https://api.esquire.co.za/Resources/Images/Products/DECO-X55-3-PACKmain2.jpg',
    ],
    tags: ['mesh wifi', 'deco', 'wifi 6', 'ax3000', '3-pack', 'whole home'],
    inStock: true,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: Category): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.shortDesc.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
}

export function getProductsByIds(ids: string[]): Product[] {
  return products.filter((p) => ids.includes(p.id));
}
