export type Category =
  | 'power-control'
  | 'lighting'
  | 'security'
  | 'environmental'
  | 'access-control'
  | 'remote-control'
  | 'water-control'
  | 'voice-assistants'
  | 'bundles';

export interface Product {
  id: string;
  slug: string;
  sku: string;
  name: string;
  shortDesc: string;
  description: string;
  category: Category;
  brand: 'Tuya' | 'Smartlife' | 'TP-Link TAPO' | 'Amazon Echo' | 'Google Nest' | 'GeeWiz';
  price: number;
  comparePrice?: number;
  images: string[];
  tags: string[];
  inStock: boolean;
  featured?: boolean;
}

export const CATEGORIES: Record<Category, string> = {
  'power-control': 'Power Control',
  'lighting': 'Lighting',
  'security': 'Security',
  'environmental': 'Environmental',
  'access-control': 'Access Control',
  'remote-control': 'Remote Control',
  'water-control': 'Water Control',
  'voice-assistants': 'Voice Assistants',
  'bundles': 'Bundles',
};

export const products: Product[] = [
  {
    id: 'gw-a-sa-smart-plug-16a',
    slug: 'wifi-smart-plug-16a-tuya',
    sku: 'GW-A-SA-PLUG-16A',
    name: 'WiFi Smart Plug 16A with Energy Monitoring',
    shortDesc: 'SA plug with Tuya/Smartlife, Alexa & Google Home. Energy monitoring included.',
    description: 'Control home appliances from anywhere using the Tuya / Smart Life app. Features voice assistant support via Amazon Alexa and Google Home, scheduling, timers, and energy monitoring. South African 16A plug type. Input: 100–240V, Max load: 16A, Wi-Fi: 2.4GHz.',
    category: 'power-control',
    brand: 'Tuya',
    price: 250,
    images: ['/images/products/gw-tuya-plug/main.jpg'],
    tags: ['smart plug', 'energy monitoring', 'alexa', 'google home', '16a', 'sa plug'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-tuya-basic-breaker-10a',
    slug: 'tuya-wifi-switch-breaker-10a-energy-monitoring',
    sku: 'GW-A-BREAKER-10A',
    name: 'Tuya WiFi Switch Breaker 10A with Energy Monitoring',
    shortDesc: 'DIN-rail smart breaker with energy monitoring, scheduling and remote control.',
    description: 'Smart circuit breaker with Tuya Wi-Fi, 10A capacity, energy monitoring (kWh), remote on/off, scheduling and overload protection. DIN rail mount. Compatible with Tuya / SmartLife, Alexa and Google Home.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-tuya-breaker-10a/main.jpg'],
    tags: ['breaker', 'din rail', 'energy monitoring', 'smart switch'],
    inStock: true,
  },
  {
    id: 'gw-a-63a-breaker-timer',
    slug: 'tuya-63a-smart-breaker-timer',
    sku: 'GW-A-STM10',
    name: '63A Tuya Smart Breaker with Timer',
    shortDesc: 'High-capacity 63A smart circuit breaker with scheduling and LED indicator.',
    description: '63A Tuya smart breaker with timer and LED indicator. Suitable for heavy-load applications including geysers, pool pumps and industrial equipment. Wi-Fi controlled via Tuya / SmartLife app.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-63a-breaker-timer/main.jpg'],
    tags: ['63a', 'breaker', 'geyser', 'pool pump', 'heavy load'],
    inStock: true,
  },
  {
    id: 'gw-a-63a-breaker-kwh',
    slug: 'tuya-63a-smart-breaker-kwh',
    sku: 'GW-A-BREAKER-63A-KWH',
    name: '63A Tuya Smart Breaker with kWh Monitoring',
    shortDesc: '63A breaker with real-time energy consumption monitoring.',
    description: '63A Tuya smart circuit breaker with kWh energy monitoring, remote control, and scheduling. Monitor energy usage of high-load devices like geysers and pool pumps in real time.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-63a-breaker-kwh/main.jpg'],
    tags: ['63a', 'energy monitoring', 'kwh', 'breaker'],
    inStock: true,
  },
  {
    id: 'gw-a-mini-diy-16a-switch',
    slug: 'mini-diy-16a-tuya-switch',
    sku: 'GW-A-MINI-16A',
    name: 'Mini DIY 16A Tuya In-Wall Switch Module',
    shortDesc: 'Compact in-wall relay module. Works with existing switches.',
    description: 'Miniature 16A Tuya smart switch module designed to fit behind existing wall switches. No neutral required. Compatible with Tuya / SmartLife, Alexa, Google Home and Home Assistant.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-mini-diy-16a/main.jpg'],
    tags: ['in-wall module', 'relay', 'no neutral', 'diy'],
    inStock: true,
  },
  {
    id: 'gw-a-1ch-inching-12v',
    slug: 'geewiz-1ch-inching-12v-tuya',
    sku: 'GW-A-1CH-12V',
    name: 'GeeWiz 1CH Inching/Self-Locking 12V Tuya Module',
    shortDesc: '12V relay module with inching/self-locking modes for gates, locks and automation.',
    description: 'Tuya 1-channel 12V relay module with inching and self-locking modes. Ideal for gate motors, door locks, blinds and custom automation projects. Wi-Fi controlled via Tuya / SmartLife.',
    category: 'power-control',
    brand: 'GeeWiz',
    price: 0,
    images: ['/images/products/gw-a-1ch-inching-12v/main.jpg'],
    tags: ['relay', '12v', 'gate', 'inching', 'automation'],
    inStock: true,
  },
  {
    id: 'gw-a-sf-2200w',
    slug: 'tuya-smart-switch-2200w',
    sku: 'GW-A-SF-2200W',
    name: 'Tuya WiFi Smart Switch 2200W',
    shortDesc: '2200W in-line smart switch for high-power appliances.',
    description: '2200W Tuya smart in-line switch for control of high-power appliances. Remote control, scheduling, and energy monitoring via Tuya / SmartLife app.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-sf-2200w/main.jpg'],
    tags: ['2200w', 'in-line switch', 'high power'],
    inStock: true,
  },
  {
    id: 'gw-a-30a-smart-switch',
    slug: 'tuya-wifi-smart-switch-30a',
    sku: 'GW-A-SW-30A',
    name: 'Tuya Wi-Fi Smart Switch 30A / 6600W',
    shortDesc: 'Heavy-duty 30A smart switch for geysers, HVAC and industrial loads.',
    description: '30A / 6600W Tuya smart switch. Ideal for geysers, water heaters, HVAC units and other high-draw appliances. Remote on/off, scheduling, and energy monitoring via Tuya / SmartLife app.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-30a-switch/main.jpg'],
    tags: ['30a', '6600w', 'geyser', 'hvac', 'heavy duty'],
    inStock: true,
  },
  {
    id: 'gw-a-energy-monitor-ms01',
    slug: 'tuya-energy-monitor-ms01',
    sku: 'GW-A-MS01',
    name: 'Tuya Energy Monitor MS01',
    shortDesc: 'Whole-home energy monitoring with real-time kWh tracking.',
    description: 'The Tuya MS01 energy monitor provides real-time whole-home energy consumption monitoring. Clips onto your mains cables without cutting. View usage, costs and trends in the Tuya / SmartLife app.',
    category: 'power-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-energy-monitor/main.jpg'],
    tags: ['energy monitor', 'whole home', 'kwh', 'electricity'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-tuya-dimmer-switch',
    slug: 'tuya-wifi-dimmer-light-switch',
    sku: 'GW-A-DIMMER',
    name: 'Tuya WiFi Smart Dimmer Light Switch',
    shortDesc: 'In-wall dimmer switch compatible with LED and halogen bulbs.',
    description: 'Tuya WiFi smart dimmer switch. Compatible with dimmable LED and halogen bulbs. No neutral required. Control brightness via app, voice or touch. Works with Alexa, Google Home and Home Assistant.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-dimmer/main.jpg'],
    tags: ['dimmer', 'led', 'light switch', 'no neutral'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-tuya-light-switch-no-neutral',
    slug: 'tuya-smart-light-switch-no-neutral',
    sku: 'GW-A-SW-NONEUTRAL',
    name: 'Tuya Smart Light Switch (No Neutral Required)',
    shortDesc: 'Drop-in smart wall switch — no neutral wire needed.',
    description: 'Tuya smart wall switch that works without a neutral wire — perfect for older SA wiring. Single gang. Touch or app control, scheduling, and voice assistant compatibility.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-tuya-light-switch/main.jpg'],
    tags: ['light switch', 'no neutral', 'in-wall', 'single gang'],
    inStock: true,
  },
  {
    id: 'gw-tuya-led-gu10-9w',
    slug: 'tuya-led-gu10-rgbcw-9w',
    sku: 'GW-TUYA-GU10-9W',
    name: 'Tuya Smart LED GU10 RGBCW 9W',
    shortDesc: 'GU10 spotlight with full RGBCW colour, dimming and scheduling.',
    description: '9W GU10 smart LED bulb with full RGB + cool/warm white (RGBCW). 16 million colours, dimmable, schedulable. Works with Tuya / SmartLife, Alexa and Google Home. Direct replacement for standard GU10 downlights.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-tuya-gu10-9w/main.jpg'],
    tags: ['gu10', 'rgb', 'smart bulb', 'spotlight', 'led'],
    inStock: true,
  },
  {
    id: 'gw-tuya-led-gu10-7w',
    slug: 'tuya-led-gu10-rgbcw-7w',
    sku: 'GW-TUYA-GU10-7W',
    name: 'Tuya Smart LED GU10 RGBCW 7W',
    shortDesc: '7W GU10 smart spotlight with RGBCW colour control.',
    description: '7W GU10 smart LED with full RGBCW colour spectrum. Ideal for accent and display lighting. Works with Tuya / SmartLife, Alexa and Google Home.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-tuya-gu10-7w/main.jpg'],
    tags: ['gu10', 'rgb', 'smart bulb', '7w', 'led'],
    inStock: true,
  },
  {
    id: 'gw-t-smart-bulb-e27-9w',
    slug: 'tuya-smart-bulb-rgb-cw-9w-e27',
    sku: 'GW-T-BULB-E27-9W',
    name: 'Tuya Smart Bulb RGBCW 9W E27',
    shortDesc: 'E27 screw-cap smart bulb with full colour and white temperature control.',
    description: 'Tuya 9W E27 smart LED bulb with 16M colour RGBCW. Dimmable. Schedulable. Music sync mode. Compatible with Tuya / SmartLife, Alexa, Google Home and Home Assistant.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-bulb-e27-9w/main.jpg'],
    tags: ['e27', 'smart bulb', 'rgb', '9w', 'screw cap'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-t-smart-bulb-b22-10w',
    slug: 'tuya-smart-bulb-rgb-cw-10w-b22',
    sku: 'GW-T-BULB-B22-10W',
    name: 'Tuya Smart Bulb RGBCW 10W B22',
    shortDesc: 'B22 bayonet smart bulb — SA standard fitting with full RGBCW.',
    description: 'Tuya 10W B22 bayonet smart LED bulb with RGBCW colour. South African standard fitting. Dimmable, schedulable, music sync. Works with Tuya / SmartLife, Alexa and Google Home.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-bulb-b22-10w/main.jpg'],
    tags: ['b22', 'bayonet', 'smart bulb', 'rgb', '10w'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-t-smart-led-downlight',
    slug: 'tuya-smart-led-downlight',
    sku: 'GW-T-DOWNLIGHT',
    name: 'Tuya Smart LED Downlight',
    shortDesc: 'Recessed smart downlight with warm/cool white dimming.',
    description: 'Tuya smart recessed LED downlight with variable colour temperature (warm to cool white) and dimming. Suitable for new builds and renovations. App, voice and wall switch compatible.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-downlight/main.jpg'],
    tags: ['downlight', 'recessed', 'dimmable', 'colour temperature'],
    inStock: true,
  },
  {
    id: 'gw-t-light-sensor',
    slug: 'tuya-light-sensor',
    sku: 'GW-T-LSENSOR',
    name: 'Tuya Light Sensor',
    shortDesc: 'Lux-based light sensor for automation triggers.',
    description: 'Tuya WiFi light sensor measures ambient lux levels. Use as an automation trigger — turn lights on at dusk, close blinds in bright sunlight, or trigger scenes based on light levels.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-light-sensor/main.jpg'],
    tags: ['light sensor', 'lux', 'automation', 'trigger'],
    inStock: true,
  },
  {
    id: 'gw-a-pir-808wt',
    slug: 'tuya-wifi-pir-detector-808wt',
    sku: 'GW-A-WL-808WT',
    name: 'Tuya WiFi PIR Motion Detector WL-808WT',
    shortDesc: 'Wi-Fi PIR motion sensor — no hub required.',
    description: 'Tuya WiFi PIR motion detector. Works standalone over Wi-Fi — no hub or zigbee gateway needed. Triggers automations, sends app alerts, and integrates with smart home scenes.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-pir-808wt/main.jpg'],
    tags: ['pir', 'motion sensor', 'wifi', 'security', 'alert'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-a-rf-pir-803w',
    slug: 'tuya-rf-433mhz-pir-detector',
    sku: 'GW-A-WL-803W',
    name: 'Tuya RF 433MHz PIR Motion Detector WL-803W',
    shortDesc: 'RF 433MHz PIR sensor — pairs with Tuya alarm hubs.',
    description: 'RF 433MHz PIR motion detector for use with Tuya-compatible alarm hubs and gateways. Battery-powered. Mounts in corners for wide-angle detection.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-rf-pir-803w/main.jpg'],
    tags: ['rf', '433mhz', 'pir', 'alarm', 'hub'],
    inStock: true,
  },
  {
    id: 'gw-a-presence-sensor-24ghz',
    slug: 'tuya-wifi-24ghz-human-presence-sensor',
    sku: 'GW-A-WL-RTCZ-03T',
    name: 'Tuya WiFi 2.4GHz Human Presence Sensor',
    shortDesc: 'mmWave radar presence sensor — detects stationary occupancy.',
    description: 'Next-gen mmWave 2.4GHz radar sensor that detects stationary human presence — not just movement. Perfect for automating lights in rooms where you sit still. Wi-Fi connected, no hub needed.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-presence-24ghz/main.jpg'],
    tags: ['presence sensor', 'mmwave', 'radar', 'stationary detection'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-a-presence-sensor-58ghz',
    slug: 'tuya-wifi-58ghz-human-presence-sensor',
    sku: 'GW-A-WL-RTCZ-05T',
    name: 'Tuya WiFi 5.8GHz Human Presence Sensor',
    shortDesc: '5.8GHz microwave presence sensor with luminance detection.',
    description: '5.8GHz microwave radar presence sensor. Detects stationary occupancy with high accuracy. Includes ambient luminance measurement for lux-based automations. Wi-Fi, no hub needed.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-presence-58ghz/main.jpg'],
    tags: ['presence sensor', '5.8ghz', 'microwave', 'lux', 'radar'],
    inStock: true,
  },
  {
    id: 'gw-a-zigbee-presence-24ghz',
    slug: 'tuya-zigbee-24ghz-presence-sensor',
    sku: 'GW-A-WL-RTCZ-03Z',
    name: 'Tuya Zigbee 2.4GHz Human Presence Sensor with Lux',
    shortDesc: 'Zigbee mmWave presence sensor with lux — pairs with Zigbee hub.',
    description: 'Zigbee 2.4GHz mmWave radar presence sensor with ambient light (lux) measurement. Requires Tuya Zigbee hub or Home Assistant with Zigbee coordinator. Ideal for local control and Home Assistant automations.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-zigbee-presence/main.jpg'],
    tags: ['zigbee', 'presence sensor', 'lux', 'home assistant'],
    inStock: true,
  },
  {
    id: 'gw-a-door-sensor-wifi',
    slug: 'tuya-wifi-door-window-sensor',
    sku: 'GW-A-WL-19JWT',
    name: 'Tuya WiFi Door/Window Magnetic Sensor',
    shortDesc: 'Wi-Fi door/window sensor — no hub required.',
    description: 'Tuya WiFi magnetic contact sensor for doors and windows. Triggers automations and push alerts when opened or closed. Works standalone over Wi-Fi — no hub needed.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-door-sensor-wifi/main.jpg'],
    tags: ['door sensor', 'window sensor', 'magnetic', 'wifi', 'alert'],
    inStock: true,
  },
  {
    id: 'gw-a-door-sensor-zigbee',
    slug: 'tuya-zigbee-door-window-sensor',
    sku: 'GW-A-WL-19JWZ',
    name: 'Tuya Zigbee Door/Window Magnetic Sensor',
    shortDesc: 'Zigbee door/window contact sensor for hub-based systems.',
    description: 'Tuya Zigbee magnetic contact sensor. Pairs with Tuya Zigbee hub or Home Assistant Zigbee coordinator. Low power consumption, reliable local control.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-door-sensor-zigbee/main.jpg'],
    tags: ['door sensor', 'zigbee', 'home assistant', 'local control'],
    inStock: true,
  },
  {
    id: 'gw-a-vibration-sensor',
    slug: 'tuya-wifi-vibration-detector',
    sku: 'GW-A-WL-72WT',
    name: 'Tuya WiFi Vibration Detector WL-72WT',
    shortDesc: 'Detects vibration and shock — for safes, windows and vehicles.',
    description: 'Tuya WiFi vibration and shock detector. Alerts you to forced entry attempts on safes, windows, doors and vehicles. Adjustable sensitivity. No hub required.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-vibration/main.jpg'],
    tags: ['vibration', 'shock', 'safe', 'break-in', 'security'],
    inStock: true,
  },
  {
    id: 'gw-t-smoke-detector',
    slug: 'tuya-wifi-smart-smoke-detector',
    sku: 'GW-T-SMOKE',
    name: 'Tuya WiFi Smart Smoke Detector',
    shortDesc: 'Wi-Fi smoke alarm with app alerts and siren.',
    description: 'Tuya WiFi photoelectric smoke detector with 85dB siren and real-time push alerts to your phone. Test button, low battery alert and interconnect support. SANS 1431 compliant.',
    category: 'environmental',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-smoke-detector/main.jpg'],
    tags: ['smoke detector', 'fire alarm', 'safety', 'wifi'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-t-water-leak',
    slug: 'tuya-wifi-smart-water-leak-detector',
    sku: 'GW-T-WATER-LEAK',
    name: 'Tuya Wi-Fi Smart Water Leak Detector',
    shortDesc: 'Instant alerts when water is detected under appliances.',
    description: 'Tuya WiFi water leak detector. Place under washing machines, dishwashers, geysers and sinks. Sends push alerts the moment water is detected. No hub required.',
    category: 'environmental',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-water-leak/main.jpg'],
    tags: ['water leak', 'flood', 'geyser', 'washing machine', 'alert'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-a-universal-remote',
    slug: 'tuya-universal-smart-remote-control',
    sku: 'GW-A-REMOTE',
    name: 'Tuya Universal Smart IR/RF Remote Control',
    shortDesc: 'Control TVs, ACs, fans and more from one app.',
    description: 'Tuya universal smart remote hub. Controls IR and RF devices — TVs, air conditioners, fans, set-top boxes and more. Learn mode for any remote. Integrates with scenes and voice assistants.',
    category: 'remote-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-universal-remote/main.jpg'],
    tags: ['remote control', 'ir', 'rf', 'air conditioner', 'tv', 'universal'],
    inStock: true,
  },
  {
    id: 'gw-a-ir-rf-combo',
    slug: 'tuya-wifi-ir-rf-universal-remote',
    sku: 'GW-A-WL-IRF',
    name: 'Tuya WiFi IR+RF 2-in-1 Universal Remote WL-IRF',
    shortDesc: 'Combined IR and RF remote in a single compact unit.',
    description: 'Dual-protocol (IR + RF) universal remote controller. One device controls both infrared devices (TVs, ACs) and RF devices (fans, roller shutters). No hub needed.',
    category: 'remote-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-ir-rf/main.jpg'],
    tags: ['ir', 'rf', 'remote', 'air conditioner', 'roller shutter'],
    inStock: true,
  },
  {
    id: 'gw-a-remote-temp',
    slug: 'tuya-wifi-remote-control-with-temperature',
    sku: 'GW-A-WL-IRTP',
    name: 'Tuya WiFi Remote Control with Temperature Sensor WL-IRTP',
    shortDesc: 'IR remote hub with built-in temperature and humidity sensor.',
    description: 'IR universal remote with integrated temperature and humidity sensor. Automate your AC based on actual room temperature. No hub required.',
    category: 'remote-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-remote-temp/main.jpg'],
    tags: ['ir remote', 'temperature', 'humidity', 'ac automation'],
    inStock: true,
  },
  {
    id: 'gw-t-video-doorbell',
    slug: 'tuya-wifi-video-doorbell-alexa',
    sku: 'GW-T-DOORBELL',
    name: 'Tuya WiFi Video Doorbell with Alexa',
    shortDesc: 'HD video doorbell with two-way audio and motion alerts.',
    description: 'Tuya WiFi video doorbell with 1080p HD camera, two-way audio, motion detection alerts and night vision. Alexa and Google Home compatible. Local storage via micro-SD card.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-video-doorbell/main.jpg'],
    tags: ['doorbell', 'camera', 'video', 'two-way audio', 'security'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-a-video-doorbell-ml1t',
    slug: 'tuya-wifi-video-doorbell-ml1t',
    sku: 'GW-A-WL-ML1T',
    name: 'Tuya WiFi Video Doorbell WL-ML1T',
    shortDesc: 'Premium video doorbell with PIR and cloud/local storage.',
    description: 'Tuya WiFi 1080p video doorbell with PIR motion detection, two-way audio, night vision, and cloud or local (micro-SD) storage. Wide-angle lens. Weatherproof.',
    category: 'security',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-video-doorbell/main.jpg'],
    tags: ['doorbell', 'camera', 'pir', 'weatherproof', 'security'],
    inStock: true,
  },
  {
    id: 'gw-t-garage-door',
    slug: 'tuya-wifi-smart-garage-door-opener',
    sku: 'GW-T-GARAGE',
    name: 'Tuya WiFi Smart Garage Door Controller',
    shortDesc: 'Open, close and monitor your garage door from anywhere.',
    description: 'Tuya WiFi garage door controller. Works with most existing garage motors. Open and close remotely, receive alerts when the door is left open, and set auto-close timers.',
    category: 'access-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-garage-door/main.jpg'],
    tags: ['garage door', 'motor', 'access control', 'remote'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-a-drawer-lock',
    slug: 'tuya-smart-drawer-lock-bt',
    sku: 'GW-A-LOCK-BT',
    name: 'Tuya Smart Drawer/Cabinet Lock (Bluetooth)',
    shortDesc: 'Bluetooth smart lock for drawers, cabinets and lockers.',
    description: 'Tuya Bluetooth smart lock for drawers, cabinets and lockers. App controlled. Access log included. Battery powered. Suitable for home, office and retail use.',
    category: 'access-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-a-drawer-lock/main.jpg'],
    tags: ['smart lock', 'cabinet', 'drawer', 'bluetooth'],
    inStock: true,
  },
  {
    id: 'gw-t-blinds-controller',
    slug: 'tuya-smart-blinds-controller',
    sku: 'GW-T-BLINDS',
    name: 'Tuya Smart Blinds/Curtain Controller',
    shortDesc: 'Automate existing roller blinds and venetian blinds.',
    description: 'Tuya smart motor controller for roller blinds and venetian blinds. App, voice and schedule control. Compatible with most existing blinds. Works with Alexa, Google Home and Home Assistant.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-blinds/main.jpg'],
    tags: ['blinds', 'curtains', 'motor', 'automation', 'roller shutter'],
    inStock: true,
  },
  {
    id: 'gw-t-curtain-opener',
    slug: 'tuya-smart-wifi-curtain-opener',
    sku: 'GW-T-CURTAIN-2PK',
    name: 'Tuya Smart WiFi Curtain Opener/Closer (2-Pack)',
    shortDesc: 'Motorise existing curtain rails — comes as a 2-pack.',
    description: 'Tuya WiFi curtain motor set (2-pack) for existing curtain rails. Retrofit installation — no rewiring. App, voice and schedule control. Works with Alexa, Google Home and Home Assistant.',
    category: 'lighting',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-curtain/main.jpg'],
    tags: ['curtains', 'motor', '2-pack', 'retrofit', 'curtain rail'],
    inStock: true,
  },
  {
    id: 'gw-t-irrigation-4zone',
    slug: 'tuya-smart-wifi-irrigation-controller-4zone',
    sku: 'GW-T-IRRIGATION-4Z',
    name: 'Tuya Smart WiFi Irrigation Controller — 4 Zone (2nd Gen)',
    shortDesc: 'Automate up to 4 garden irrigation zones from your phone.',
    description: 'Tuya 2nd-gen WiFi irrigation controller with 4 independent zones. Schedule watering by zone, duration and frequency. App control, rain skip automation. Works with Alexa and Google Home.',
    category: 'water-control',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-t-irrigation/main.jpg'],
    tags: ['irrigation', 'garden', '4 zone', 'watering', 'outdoor'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-p-load-shedding-pack',
    slug: 'tuya-load-shedding-detector-pack',
    sku: 'GW-P-LSPACK',
    name: 'TUYA Load Shedding Detector Pack',
    shortDesc: 'SA-specific pack to detect and automate around load shedding.',
    description: 'South Africa-specific load shedding automation pack. Detects when power is cut and restored. Automate lights, geysers and devices to respond intelligently to load shedding schedules.',
    category: 'bundles',
    brand: 'Tuya',
    price: 0,
    images: ['/images/products/gw-p-load-shedding/main.jpg'],
    tags: ['load shedding', 'eskom', 'automation', 'south africa', 'bundle'],
    inStock: true,
    featured: true,
  },
  {
    id: 'gw-t-echo-pop',
    slug: 'amazon-echo-pop-cypress-green',
    sku: 'GW-T-ECHO-POP',
    name: 'Amazon Echo Pop — Cypress Green',
    shortDesc: 'Compact Alexa smart speaker. Control your Tuya devices by voice.',
    description: 'Amazon Echo Pop with Alexa. Compact smart speaker that pairs with all Tuya and Smartlife devices. Ask Alexa to control lights, switches, plugs and scenes by voice. Cypress Green colour.',
    category: 'voice-assistants',
    brand: 'Amazon Echo',
    price: 0,
    images: ['/images/products/gw-t-echo-pop/main.jpg'],
    tags: ['alexa', 'amazon echo', 'voice assistant', 'speaker'],
    inStock: true,
  },
  {
    id: 'gw-t-echo-dot-5',
    slug: 'amazon-echo-dot-5th-gen-deep-sea-blue',
    sku: 'GW-T-ECHO-DOT5',
    name: 'Amazon Echo Dot 5th Gen — Deep Sea Blue',
    shortDesc: 'Popular Alexa smart speaker with improved sound.',
    description: 'Amazon Echo Dot (5th Gen, 2022). Improved sound quality vs previous generation. Built-in Alexa for voice control of your smart home. Motion sensor for proximity automations. Deep Sea Blue.',
    category: 'voice-assistants',
    brand: 'Amazon Echo',
    price: 0,
    images: ['/images/products/gw-t-echo-dot5/main.jpg'],
    tags: ['alexa', 'echo dot', 'voice assistant', 'speaker', '5th gen'],
    inStock: true,
  },
  {
    id: 'gw-t-echo-show-5',
    slug: 'amazon-echo-show-5-3rd-gen-glacier-white',
    sku: 'GW-T-ECHO-SHOW5',
    name: 'Amazon Echo Show 5 (3rd Gen, 2023) — Glacier White',
    shortDesc: 'Smart display with Alexa, 2MP camera and video calling.',
    description: 'Amazon Echo Show 5 (3rd Gen, 2023). 5.5" touchscreen smart display with Alexa. 2MP camera for video calls, smart home dashboard, media playback and routines. Glacier White.',
    category: 'voice-assistants',
    brand: 'Amazon Echo',
    price: 0,
    images: ['/images/products/gw-t-echo-show5/main.jpg'],
    tags: ['alexa', 'echo show', 'smart display', 'video calls', '2023'],
    inStock: true,
  },
  {
    id: 'gw-t-nest-mini-2',
    slug: 'google-nest-mini-2-chalk',
    sku: 'GW-T-NEST-MINI2',
    name: 'Google Nest Mini (2nd Gen) — Chalk',
    shortDesc: 'Google Assistant smart speaker for voice control.',
    description: 'Google Nest Mini 2nd Gen. Wall-mountable smart speaker with Google Assistant. Control compatible smart home devices by voice. Stream music and answer questions. Chalk colour.',
    category: 'voice-assistants',
    brand: 'Google Nest',
    price: 0,
    images: ['/images/products/gw-t-nest-mini/main.jpg'],
    tags: ['google assistant', 'nest mini', 'voice assistant', 'speaker'],
    inStock: true,
  },
  {
    id: 'gw-10k-powerbank',
    slug: '10000mah-20w-powerbank-pd',
    sku: 'GW-PB-10K-20W',
    name: '10,000mAh 20W PD Power Bank',
    shortDesc: 'Fast-charge power bank — keep devices powered during load shedding.',
    description: '10,000mAh portable power bank with 20W Power Delivery (PD) fast charging. USB-C and USB-A outputs. Keep phones, tablets and smart home hubs powered during load shedding.',
    category: 'power-control',
    brand: 'GeeWiz',
    price: 0,
    images: ['/images/products/gw-powerbank/main.jpg'],
    tags: ['power bank', 'load shedding', 'fast charge', 'pd', '20w'],
    inStock: true,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: Category): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.shortDesc.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
}

export function getProductsByIds(ids: string[]): Product[] {
  return products.filter((p) => ids.includes(p.id));
}
